steps:
  # Nome, descrição do que tu vai fazer
  - id: "Step 00 - Realizando docker-compose up"
    #Imagem que o CI service vai chamar, $PROJECT_ID é o project id do GCP
    name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: ['-f', 'docker-compose.prod.yaml', 'up', '-d','--build']

  - id: "Step 001 - chown in /var/www"
    name: 'docker'
    args: ['logs','micro-videos-app']

  - id: "Step 01 - chown in /var/www"
    name: 'docker'
    args: ['exec','-u','root','-t','micro-videos-app','chown','-R','www-data:www-data','/var/www']

  - id: 'Step 02 - Rodando composer install'
    name: 'docker'
    args: ['exec', '-t', 'micro-videos-app', 'composer', 'install']

  - id: 'Step 04 - Copiando .env'
    name: 'docker'
    args: ['exec', '-t', 'micro-videos-app', 'cp', '.env.example', '.env']

  - id: 'Step 05 - Copiando .env.testing'
    name: 'docker'
    args: ['exec', '-t', 'micro-videos-app', 'cp', '.env.testing.example', '.env.testing']

  - id: 'Step 06 - Key generate'
    name: 'docker'
    args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'key:generate']

  - id: 'Step 07 - Migrations'
    name: 'docker'
    args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'migrate']

  - id: 'Step 08 - Executar'
    name: 'docker'
    args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']
