# cloudbuild.yaml
# Rodar com:
# gcloud builds submit . --config=cloudbuild.yaml --no-cache

options:
  env:
    - DOCKER_HOST=tcp://docker:2375
    - DOCKER_DRIVER=overlay2
  volumes:
    - name: docker-graph-storage
      path: /docker-graph-storage

steps:
  # Step 1: Sobe o Docker-in-Docker
  - id: "Start Docker Daemon"
    name: "docker:20.10-dind"
    args: ["dockerd", "--host=tcp://0.0.0.0:2375"]
    privileged: true
    volumes:
      - name: docker-graph-storage
        path: /docker-graph-storage

  # Step 2: Sobe containers com docker-compose
  - id: "Docker Compose Up"
    name: "docker/compose:1.28.2"
    args: ["-f", "docker-compose.prod.yaml", "up", "-d"]

  # Step 3: Ajusta permissões
  - id: "Chown /var/www"
    name: "docker"
    args: ["exec", "-u", "root", "-t", "micro-videos-app", "chown", "-R", "www-data:www-data", "/var/www"]

  # Step 4: Composer install
  - id: "Composer Install"
    name: "docker"
    args: ["exec", "-t", "micro-videos-app", "composer", "install"]

  # Step 5: Copiar arquivos .env
  - id: "Copy envs"
    name: "docker"
    args: ["exec", "-t", "micro-videos-app", "bash", "-c", "cp .env.example .env && cp .env.testing.example .env.testing"]

  # Step 6: Artisan key generate
  - id: "Key Generate"
    name: "docker"
    args: ["exec", "-t", "micro-videos-app", "php", "/var/www/artisan", "key:generate"]

  # Step 7: Migrations
  - id: "Migrate"
    name: "docker"
    args: ["exec", "-t", "micro-videos-app", "php", "/var/www/artisan", "migrate"]

  # Step 8: PHPUnit
  - id: "Run PHPUnit"
    name: "docker"
    args: ["exec", "-t", "micro-videos-app", "php", "/var/www/vendor/bin/phpunit", "-c", "/var/www/phpunit.xml"]

tags: ['ci', 'laravel', 'docker-compose']
