steps:
  # Nome, descrição do que tu vai fazer
  - id: "Step 00 - Realizando docker-compose up"
    #Imagem que o CI service vai chamar, $PROJECT_ID é o project id do GCP
    name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: ['-f', 'docker-compose.yaml', 'up', '-d']
