<?php

namespace Tests\Unit\Models;

use App\Models\CastMember;
use App\Models\Traits\Uuid;
use Illuminate\Database\Eloquent\SoftDeletes;
use Tests\TestCase;
use Tests\Traits\TestDates;

class CastMemberTest extends TestCase
{
    use TestDates;

    private $castMember;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->castMember = new CastMember();
    }

    public function getModel()
    {
        return $this->castMember;
    }

    public function testFillable()
    {
        $fillable =  [
            'name',
            'type'
        ];

        $this->assertEquals($fillable, $this->castMember->getFillable());
    }

    public function testUseRequiredTraits()
    {
        $traits = [
            SoftDeletes::class,
            Uuid::class
        ];

        $classUsedClasses = array_keys(class_uses(CastMember::class));

        $this->assertEquals($traits,$classUsedClasses);
    }

    public function testKeyType()
    {
        $keyType = 'string';
        $this->assertEquals($keyType, $this->castMember->getKeyType());
    }

    public function testIncrementing()
    {
        $this->assertFalse($this->castMember->incrementing);
    }
}
